using System;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;
using CodeValue.CodeLight.Client.Foundation;

namespace Patients.Client.Common.CommonTypes
{
    //TODO: This class need to be code generated by Bernie
    public class Patient : NotifyPropertyChanged
    {
        private string _id;
        public string Id
        {
            get { return _id; }
            set { _id = value; 
            OnPropertyChanged(() => Id);}
        }

        private string _name;
        public string Name
        {
            get { return _name; }
            set { _name = value;
            OnPropertyChanged(() => Name);
            }
        }
    }
}
